version: '3'
services:
  graphql.pagevamp.pv:
    container_name: graphql.pagevamp.pv
    image: pagevamp/nginx-php7-fpm:7.2
    restart: always
    environment:
      - VIRTUAL_HOST=graphql.pagevamp.pv,grey-graphql.pagevamp.pv
    volumes:
      - ./:/var/www
      - ./docker/sites/default.conf:/etc/nginx/sites-enabled/default
      - ./docker/sites/php.ini:/etc/php/7.2/fpm/php.ini

    networks:
      - pagevamp
networks:
  pagevamp:
    external: true
